
let validatorFirst = new Validator('[name=first-name]')
let validatorLast = new Validator('[name=last-name]')
let validatorEmail = new EmailValidator('[name=email]')
let validatorDay = new DayValidator('[name=day]')
let validatorLength = new DateLengthValidator('[name=day]')
let validatorNumber = new NumberValidator('[name=day]')
let validatorMonth = new MonthValidator('[name=month]')
let validatorMonthLength = new DateLengthValidator('[name=month]')
let validatorMonthNumber = new NumberValidator('[name=month]')
let validatorYearLength = new DateLengthValidator('[name=year]')
let validatorYearNumber = new NumberValidator('[name=year]')
let validatorPasswordSpecial = new SpecialCharactersValidator('[name=password]')
// let validatorPasswordMixedCase = new MixedCaseValidator('[name=password]')